#!/usr/bin/bash
hda-verb /dev/snd/hwC0D0 0x20 SET_COEF_INDEX 0x67
hda-verb /dev/snd/hwC0D0 0x20 SET_PROC_COEF 0x3000

ws1="1:   Terminal"

i3-resurrect restore -w "$ws1"

firefox &
discord &
steam &

