#!/usr/bin/bash
hda-verb /dev/snd/hwC0D0 0x20 SET_COEF_INDEX 0x67
hda-verb /dev/snd/hwC0D0 0x20 SET_PROC_COEF 0x3000

i3-resurrect restore -w "$PROFILE_WS1_NAME"
crontab -l > ~/.dotfiles/profiles/johan/my-crontab

firefox &
discord &
steam &
pulseeffects --gapplication-service &

mount ~/nextcloud
