#!/usr/bin/bash

crontab -l > ~/.dotfiles/profiles/johan/my-crontab

pulseeffects --gapplication-service &
espanso daemon &
mpDris2 &

ferdi &
st &
firefox &

sudo hda-verb /dev/snd/hwC0D0 0x20 SET_COEF_INDEX 0x67
sudo hda-verb /dev/snd/hwC0D0 0x20 SET_PROC_COEF 0x3000
