#!/usr/bin/bash

# Add all repos in here so that other scripts can access them
# For example the git-auto-updater or git-status-check
REPOS=(
	~/.dotfiles
	~/repos/farbs
  ~/repos/dwm
  ~/repos/dwmblocks
  ~/repos/dmenu
  ~/repos/wallpapers
)
