#!/usr/bin/bash

crontab -l > ~/.dotfiles/profiles/johan/my-crontab
gnome-keyring-daemon --start --components=secrets

pulseeffects --gapplication-service &
espanso daemon &
mpDris2 &

st &
ferdi &
firefox &
