#!/usr/bin/bash
crontab -l > ~/.dotfiles/profiles/johan/my-crontab
gnome-keyring-daemon --start --components=secrets

xrandr -r 120 &

firefox &
ferdi &
#nextcloud &
pulseeffects --gapplication-service &
mpDris2 &
espanso daemon &
