#!/usr/bin/bash

xrandr --output DisplayPort-0 --mode 2560x1440 --rate 144 --pos 1920x-190 --rotate normal --output DisplayPort-2 --mode 1920x1080 --rate 144 --pos 0x0 --rotate normal
# xrandr --output DisplayPort-0 --mode 2560x1440 --pos 0x0 --rate 144
# xrandr --output DisplayPort-2 --mode 1920x1080 --pos 0x0 --rate 144 --left-of DisplayPort-0
